name: the_black_store
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_switch: ^0.3.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  conditional_builder_null_safety: ^0.0.6
  equatable: ^2.0.5
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/bottom_nav_bar/



  fonts:
   - family: Almarai
     fonts:
       - asset: assets/fonts/Almarai-Bold.ttf
       - asset: assets/fonts/Almarai-Regular.ttf
       - asset: assets/fonts/Almarai-Regular.ttf
         weight: 700
